### ISSUE TITLE
Support for Digitone Project .dnprj possible?

### ISSUE THREAD

**Issue by jhalitschke** [dagargo/elektroid#49]
Is it possible to transfer also project files to Digitone devices? 
My Digitone is shown as MIDI device, but the file browser on the left doesn't recognize .dnprj files.

Running Elektroid 1.3 on Ubuntu Studio 20

**Comment by dagargo** [comment]
Hi, @jhalitschke!

Did you manage to try this? I'm really interested as version 2.0 depends mostly on the feedback and I haven't got much.

**Comment by lentferj** [comment]
@dagargo - I just got myself a Digitone (after realizing how good overwitch support for my Digitakt is ;) ). I will hopefully be able to check this next week. Should arrive on Monday.

**Comment by dagargo** [comment]
Really glad to hear that, @lentferj. :smile: 

I hope you'll enjoy it twice. :grin:

**Comment by lentferj** [comment]
I would propably need an example .dnprj file to upload?

**Comment by lentferj** [comment]
I created a tiny test project and saved it... I can't see it in elektroid, tough

![grafik](https://user-images.githubusercontent.com/5664183/142869608-eca22d7d-9c08-4ece-9826-b834d23ef463.png)

**Comment by dagargo** [comment]
There are several things that may cause this behaviour.

* Perhaps, it could be that the view does not get refreshed although it can read the data. What happens if you click on the reload button?
* Another option could be that there is a permission issue. Probably you have checked this up already but, can you post the output of `ls -la /home/lentferj/tmp/elektroid` and `ps -fea | grep elektroid`?
* Finally, most probably it's a bug unrelated to these ideas. I've checked up the code and tested this on my Digitakt and it just works.

Let's check the first and second ideas now and we'll continue with the possible bugs afterwards.

However, try run a small test with `elektroid -vv` that fails and post the output here.

**Comment by lentferj** [comment]
```
$ ls -la /home/lentferj/tmp/elektroid ; ps -fea | grep elektroid
insgesamt 20
drwxr-xr-x  4 lentferj lentferj   44 Nov 22 14:30 .
drwxr-xr-x 23 lentferj lentferj 4096 Nov 22 21:00 ..
drwxr-xr-x  2 lentferj lentferj    6 Nov 22 14:30 foobar
drwxr-xr-x  2 lentferj lentferj 4096 Nov 22 14:19 H
-rw-r--r--  1 lentferj lentferj 4501 Nov 22 14:18 TEST.dnprj
lentferj 10098 27009  4 21:06 pts/5    00:00:00 elektroid -l /home/lentferj/tmp/elektroid/
lentferj 10115 14010  0 21:06 pts/4    00:00:00 grep --color=auto elektroid
```
If I press reload or even restart elektroid still nothing shows up.

 It does work fine for my Digitakt, but not for Digitone... which is strange, because it's the computer side, not the Elektron side.
 
 
![grafik](https://user-images.githubusercontent.com/5664183/142928605-1d6d1672-307a-4323-af7e-989af0149f32.png)

But it must have something todo with my local path.. 


![grafik](https://user-images.githubusercontent.com/5664183/142928795-6eaf8523-fa05-4b66-9b78-9384a932f690.png)

Let me recheck this ..........

**Comment by lentferj** [comment]
Changing the path didn't help anything

![grafik](https://user-images.githubusercontent.com/5664183/142929250-226db7f5-56cb-4904-a4c1-f004eeab5935.png)

```

$ elektroid -vv -l /home/lentferj/elektroid
DEBUG:utils.c:209:(get_local_startup_path): Using '/home/lentferj/elektroid' as local dir...
DEBUG:audio.c:258:(audio_init): Initializing audio...
DEBUG:connector.c:2626:(connector_get_system_device): Adding hw:8 (Elektron Digitone) Elektron Digitone MIDI 1...
DEBUG:connector.c:2626:(connector_get_system_device): Adding hw:9 (Elektron Digitakt) Elektron Digitakt MIDI 1...
DEBUG:elektroid.c:329:(elektroid_load_devices): Loading devices...
DEBUG:elektroid.c:347:(elektroid_load_devices): Selecting device -1...
DEBUG:elektroid.c:1251:(elektroid_stop_load_thread): Stopping load thread...
DEBUG:elektroid.c:3234:(elektroid_run): Creating notifier thread...
DEBUG:notifier.c:42:(notifier_set_dir): Changing notifier path to /home/lentferj/elektroid...
DEBUG:connector.c:2626:(connector_get_system_device): Adding hw:8 (Elektron Digitone) Elektron Digitone MIDI 1...
DEBUG:connector.c:2626:(connector_get_system_device): Adding hw:9 (Elektron Digitakt) Elektron Digitakt MIDI 1...
DEBUG:elektroid.c:329:(elektroid_load_devices): Loading devices...
DEBUG:elektroid.c:347:(elektroid_load_devices): Selecting device -1...
DEBUG:elektroid.c:1251:(elektroid_stop_load_thread): Stopping load thread...
DEBUG:connector.c:2626:(connector_get_system_device): Adding hw:8 (Elektron Digitone) Elektron Digitone MIDI 1...
DEBUG:connector.c:2626:(connector_get_system_device): Adding hw:9 (Elektron Digitakt) Elektron Digitakt MIDI 1...
DEBUG:elektroid.c:329:(elektroid_load_devices): Loading devices...
DEBUG:elektroid.c:347:(elektroid_load_devices): Selecting device -1...
DEBUG:elektroid.c:1251:(elektroid_stop_load_thread): Stopping load thread...
DEBUG:connector.c:2427:(connector_init): Initializing connector to 'hw:8'...
DEBUG:connector.c:2436:(connector_init): Setting blocking mode...
DEBUG:connector.c:2448:(connector_init): Stopping device...
DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (13): f0 00 20 3c 10 00 00 00 00 00 00 01 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (5): 00 00 00 00 01
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (45): f0 00 20 3c 10 00 04 00 0f 00 00 01 14 11 00 01 02 03 50 52 51 53 00 54 55 56 57 58 59 5a 00 5b 5c 5d 44 69 67 69 00 74 6f 6e 65 00 f7
DEBUG:connector.c:1388:(connector_rx): Raw message received (45): f0 00 20 3c 10 00 04 00 0f 00 00 01 14 11 00 01 02 03 50 52 51 53 00 54 55 56 57 58 59 5a 00 5b 5c 5d 44 69 67 69 00 74 6f 6e 65 00 f7
DEBUG:connector.c:1396:(connector_rx): Message received (33): 00 0f 00 00 81 14 11 01 02 03 50 52 51 53 54 55 56 57 58 59 5a 5b 5c 5d 44 69 67 69 74 6f 6e 65 00
DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (13): f0 00 20 3c 10 00 00 00 01 00 00 02 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (5): 00 01 00 00 02
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (25): f0 00 20 3c 10 00 04 00 10 00 01 02 30 30 00 35 31 00 31 2e 33 31 00 00 f7
DEBUG:connector.c:1388:(connector_rx): Raw message received (25): f0 00 20 3c 10 00 04 00 10 00 01 02 30 30 00 35 31 00 31 2e 33 31 00 00 f7
DEBUG:connector.c:1396:(connector_rx): Message received (15): 00 10 00 01 82 30 30 35 31 00 31 2e 33 31 00
DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (13): f0 00 20 3c 10 00 00 00 02 00 00 03 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (5): 00 02 00 00 03
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (18): f0 00 20 3c 10 00 06 00 11 00 02 03 6d 28 40 0f 71 f7
DEBUG:connector.c:1388:(connector_rx): Raw message received (18): f0 00 20 3c 10 00 06 00 11 00 02 03 6d 28 40 0f 71 f7
DEBUG:connector.c:1396:(connector_rx): Message received (9): 00 11 00 02 83 ed 28 8f 71
DEBUG:connector.c:2536:(connector_init): UID: 718f28ed
DEBUG:connector.c:2544:(connector_init): Connected to Digitone 1.31 (Digitone)
DEBUG:elektroid.c:2465:(elektroid_fill_fs_combo): Selecting first filesystem...
DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (36): f0 00 20 3c 10 00 00 00 03 00 00 53 2f 70 00 72 6f 6a 65 63 74 73 00 2f 00 00 00 00 00 00 00 00 00 00 01 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (25): 00 03 00 00 53 2f 70 72 6f 6a 65 63 74 73 2f 00 00 00 00 00 00 00 00 00 01
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (113): f0 00 20 3c 10 00 04 00 12 00 03 53 01 00 00 00 00 00 00 00 00 04 00 00 00 00 03 50 52 45 00 53 45 54 53 00 00 02 00 00 00 00 01 00 40 00 00 00 00 12 01 01 53 45 00 57 20 50 52 4f 4a 45 00 43
DEBUG:connector.c:1388:(connector_rx): Raw message received (113): f0 00 20 3c 10 00 04 00 12 00 03 53 01 00 00 00 00 00 00 00 00 04 00 00 00 00 03 50 52 45 00 53 45 54 53 00 00 02 00 00 00 00 01 00 40 00 00 00 00 12 01 01 53 45 00 57 20 50 52 4f 4a 45 00 43...
DEBUG:connector.c:1396:(connector_rx): Message received (92): 00 12 00 03 d3 01 00 00 00 00 00 00 00 04 00 00 00 03 50 52 45 53 45 54 53 00 00 02 00 00 00 01 00 40 00 00 00 12 01 01 53 45 57 20 50 52 4f 4a 45 43 54 00 00 02 00 00 00 02 00 40 00 00 00 7e...
```

**Comment by lentferj** [comment]
Ok, I don't know what's going on. If I use the local path that I also use for my Digitakt, then it seems to be all fine. But is this how it is intended to work? I mean I am passing the local path on the cli. I even removed ~/.config/elektroid/preferences.json. Still it would not show the content of /home/lentferj/elektroid ... but it does for .....

![grafik](https://user-images.githubusercontent.com/5664183/142932950-fec9f910-fe3a-4854-b8e4-34ca85ff99be.png)

**Comment by lentferj** [comment]
But at least I can confirm, that I can download and upload projects to digitone (when I am able to access them in the gui).

**Comment by dagargo** [comment]
A bit of background.

The `-l` option was intended to open `elektroid` with the selected local directory. The use case was to open it from the file manager or an audio editor if they allow to do this. BTW, I have configured Nautilus (GNOME files) this way.

At the moment, added a lot of commits ago but not made public yet, `elektroid` stores two parameters in its configuration, which are auto play and the local path so it remembers the last local path you used.

So, typically, you don't need to use the parameter `-l` at all.

---

Local (left) browser should behave as any other file manager application. It's completely independent from the selected device with the exception of the appropriate file extensions.

I simulated a Digitone configuration and it worked and, as it works for some dirs, probably it's a weird permission issue.

Totally unrelated, I've noticed that the progress stops at 50% although it's completed. But I know what's this. I'll fix it tomorrow.

**Comment by dagargo** [comment]
I've pushed 97dc01dc65cadbe713177ecf7c92ad4d0a1c7f79, which will hopefully fix the issue with the progress bar.

Regarding the issue you're having with the local browser, have you manage to see whet is causing the issue? I've been thinking about this and I'd like to see just the log when you click on reload. Perhaps we'll see something in there.

**Comment by lentferj** [comment]
Progress bar seems to work now
```

$ LANG=C elektroid -vv -l /home/lentferj/tmp/elektroid/
DEBUG:utils.c:209:(get_local_startup_path): Using '/home/lentferj/tmp/elektroid' as local dir...
DEBUG:audio.c:258:(audio_init): Initializing audio...
DEBUG:connector.c:2626:(connector_get_system_device): Adding hw:8 (Elektron Digitone) Elektron Digitone MIDI 1...
DEBUG:elektroid.c:329:(elektroid_load_devices): Loading devices...
DEBUG:elektroid.c:347:(elektroid_load_devices): Selecting device 0...
DEBUG:connector.c:2427:(connector_init): Initializing connector to 'hw:8'...
DEBUG:connector.c:2436:(connector_init): Setting blocking mode...
DEBUG:connector.c:2448:(connector_init): Stopping device...
DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (13): f0 00 20 3c 10 00 00 00 00 00 00 01 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (5): 00 00 00 00 01
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (45): f0 00 20 3c 10 00 04 00 33 00 00 01 14 11 00 01 02 03 50 52 51 53 00 54 55 56 57 58 59 5a 00 5b 5c 5d 44 69 67 69 00 74 6f 6e 65 00 f7
DEBUG:connector.c:1388:(connector_rx): Raw message received (45): f0 00 20 3c 10 00 04 00 33 00 00 01 14 11 00 01 02 03 50 52 51 53 00 54 55 56 57 58 59 5a 00 5b 5c 5d 44 69 67 69 00 74 6f 6e 65 00 f7
DEBUG:connector.c:1396:(connector_rx): Message received (33): 00 33 00 00 81 14 11 01 02 03 50 52 51 53 54 55 56 57 58 59 5a 5b 5c 5d 44 69 67 69 74 6f 6e 65 00
DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (13): f0 00 20 3c 10 00 00 00 01 00 00 02 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (5): 00 01 00 00 02
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (25): f0 00 20 3c 10 00 04 00 34 00 01 02 30 30 00 35 31 00 31 2e 33 31 00 00 f7
DEBUG:connector.c:1388:(connector_rx): Raw message received (25): f0 00 20 3c 10 00 04 00 34 00 01 02 30 30 00 35 31 00 31 2e 33 31 00 00 f7
DEBUG:connector.c:1396:(connector_rx): Message received (15): 00 34 00 01 82 30 30 35 31 00 31 2e 33 31 00
DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (13): f0 00 20 3c 10 00 00 00 02 00 00 03 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (5): 00 02 00 00 03
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (18): f0 00 20 3c 10 00 06 00 35 00 02 03 6d 28 40 0f 71 f7
DEBUG:connector.c:1388:(connector_rx): Raw message received (18): f0 00 20 3c 10 00 06 00 35 00 02 03 6d 28 40 0f 71 f7
DEBUG:connector.c:1396:(connector_rx): Message received (9): 00 35 00 02 83 ed 28 8f 71
DEBUG:connector.c:2536:(connector_init): UID: 718f28ed
DEBUG:connector.c:2544:(connector_init): Connected to Digitone 1.31 (Digitone)
DEBUG:elektroid.c:2465:(elektroid_fill_fs_combo): Selecting first filesystem...
DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (36): f0 00 20 3c 10 00 00 00 03 00 00 53 2f 70 00 72 6f 6a 65 63 74 73 00 2f 00 00 00 00 00 00 00 00 00 00 01 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (25): 00 03 00 00 53 2f 70 72 6f 6a 65 63 74 73 2f 00 00 00 00 00 00 00 00 00 01
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (135): f0 00 20 3c 10 00 04 00 36 00 03 53 01 00 00 00 00 00 00 00 00 05 00 00 00 00 04 50 52 45 00 53 45 54 53 00 00 02 00 00 00 00 01 00 40 00 00 00 00 12 01 01 53 45 00 57 20 50 52 4f 4a 45 00 43
DEBUG:connector.c:1388:(connector_rx): Raw message received (135): f0 00 20 3c 10 00 04 00 36 00 03 53 01 00 00 00 00 00 00 00 00 05 00 00 00 00 04 50 52 45 00 53 45 54 53 00 00 02 00 00 00 00 01 00 40 00 00 00 00 12 01 01 53 45 00 57 20 50 52 4f 4a 45 00 43...
DEBUG:connector.c:1396:(connector_rx): Message received (112): 00 36 00 03 d3 01 00 00 00 00 00 00 00 05 00 00 00 04 50 52 45 53 45 54 53 00 00 02 00 00 00 01 00 40 00 00 00 12 01 01 53 45 57 20 50 52 4f 4a 45 43 54 00 00 02 00 00 00 02 00 40 00 00 00 7e...
DEBUG:elektroid.c:3234:(elektroid_run): Creating notifier thread...
DEBUG:notifier.c:42:(notifier_set_dir): Changing notifier path to /home/lentferj/tmp/elektroid...

<<<<<<< RELOAD >>>>>>>>>>>>>

DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (36): f0 00 20 3c 10 00 00 00 04 00 00 53 2f 70 00 72 6f 6a 65 63 74 73 00 2f 00 00 00 00 00 00 00 00 00 00 01 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (25): 00 04 00 00 53 2f 70 72 6f 6a 65 63 74 73 2f 00 00 00 00 00 00 00 00 00 01
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (135): f0 00 20 3c 10 00 04 00 37 00 04 53 01 00 00 00 00 00 00 00 00 05 00 00 00 00 04 50 52 45 00 53 45 54 53 00 00 02 00 00 00 00 01 00 40 00 00 00 00 12 01 01 53 45 00 57 20 50 52 4f 4a 45 00 43
DEBUG:connector.c:1388:(connector_rx): Raw message received (135): f0 00 20 3c 10 00 04 00 37 00 04 53 01 00 00 00 00 00 00 00 00 05 00 00 00 00 04 50 52 45 00 53 45 54 53 00 00 02 00 00 00 00 01 00 40 00 00 00 00 12 01 01 53 45 00 57 20 50 52 4f 4a 45 00 43...
DEBUG:connector.c:1396:(connector_rx): Message received (112): 00 37 00 04 d3 01 00 00 00 00 00 00 00 05 00 00 00 04 50 52 45 53 45 54 53 00 00 02 00 00 00 01 00 40 00 00 00 12 01 01 53 45 57 20 50 52 4f 4a 45 43 54 00 00 02 00 00 00 02 00 40 00 00 00 7e...
```
![grafik](https://user-images.githubusercontent.com/5664183/143440279-0844de7a-c9a2-4ef4-9b5c-5f7fee3ce988.png)

I am pretty sure it is not a privileges thing, as I coud download  FUN01.dnprj with elektroid and it is stored on-disk.
```
lentferj@ts-d20:~/tmp/elektroid$ LANG=C ls -al
total 56
drwxr-xr-x  2 lentferj lentferj    24 Nov 25 13:13 .
drwxr-xr-x 23 lentferj lentferj  4096 Nov 25 13:13 ..
-rw-r--r--  1 lentferj lentferj 50714 Nov 25 13:13 FUN01.dnprj
```

**Comment by dagargo** [comment]
I pushed e341f9972d6454cbaa352b7fcf4d3c72153630b5, which clears the filesystem combo before filling it up with the filesystems of the device.

**Comment by dagargo** [comment]
Regarding the reloading test, I think I didn't explain myself.

I'd like you to try to reload the computer browser. This is the reloading of the device side.

```
<<<<<<< RELOAD >>>>>>>>>>>>>

DEBUG:connector.c:1100:(connector_rx_drain): Draining buffer...
DEBUG:connector.c:1084:(connector_tx): Raw message sent (36): f0 00 20 3c 10 00 00 00 04 00 00 53 2f 70 00 72 6f 6a 65 63 74 73 00 2f 00 00 00 00 00 00 00 00 00 00 01 f7
DEBUG:connector.c:1089:(connector_tx): Message sent (25): 00 04 00 00 53 2f 70 72 6f 6a 65 63 74 73 2f 00 00 00 00 00 00 00 00 00 01
DEBUG:connector.c:1220:(connector_rx_raw): Buffer content (135): f0 00 20 3c 10 00 04 00 37 00 04 53 01 00 00 00 00 00 00 00 00 05 00 00 00 00 04 50 52 45 00 53 45 54 53 00 00 02 00 00 00 00 01 00 40 00 00 00 00 12 01 01 53 45 00 57 20 50 52 4f 4a 45 00 43
DEBUG:connector.c:1388:(connector_rx): Raw message received (135): f0 00 20 3c 10 00 04 00 37 00 04 53 01 00 00 00 00 00 00 00 00 05 00 00 00 00 04 50 52 45 00 53 45 54 53 00 00 02 00 00 00 00 01 00 40 00 00 00 00 12 01 01 53 45 00 57 20 50 52 4f 4a 45 00 43...
DEBUG:connector.c:1396:(connector_rx): Message received (112): 00 37 00 04 d3 01 00 00 00 00 00 00 00 05 00 00 00 04 50 52 45 53 45 54 53 00 00 02 00 00 00 01 00 40 00 00 00 12 01 01 53 45 57 20 50 52 4f 4a 45 43 54 00 00 02 00 00 00 02 00 40 00 00 00 7e...
```

**Comment by lentferj** [comment]
oh boy, that is quite obvious.. my bad :) That happens when you just want to test something quickly "in between"...
But actually, when I hit reload on the computer browser nothing is written to the console :/, even though I run with -vv.

**Comment by dagargo** [comment]
I've been studying this issue I haven't been able to locate the issue.

I'd like you to try to debug this because I'm out of ideas. Here you have some hints.

* As the refresh button does not work, let's try to fix that.
* Focus on this whole function as the bug may be hidden among its lines.

https://github.com/dagargo/elektroid/blob/65a665df73cc6eb65305ea5276d94fdbb27b1f8c/src/browser.c#L272-L282

We'll continue after seeing your findings.

**Comment by lentferj** [comment]
I added some debugging out put... (see below).

This is what I get for a "working" session:
```
lentferj@ts-d20:~/git-repos/elektroid-local$ src/elektroid  -l /home/lentferj/Samples/Elektron
BROWSER_RESET
ELEKTROID_DIR: D
ext does not exist
ELEKTROID_DIR: D
ext does not exist
ELEKTROID_DIR: D
ext does not exist
ELEKTROID_DIR: D
ext does not exist
BROWSER_RESET
ELEKTROID_DIR: D
item equals ELEKTROID_DIR
ELEKTROID_DIR: D
item equals ELEKTROID_DIR
```
and this for a session where the local browser windows remains empty:
```
lentferj@ts-d20:~/git-repos/elektroid-local$ src/elektroid  -l ~/tmp/elektroid/
BROWSER_RESET
ELEKTROID_DIR: D
ext does not exist
ELEKTROID_DIR: D
ext does not exist
ELEKTROID_DIR: D
ext does not exist
ELEKTROID_DIR: D
ext does not exist
BROWSER_RESET
```



```
diff --git a/src/browser.c b/src/browser.c
index ff56985..a90d24a 100644
--- a/src/browser.c
+++ b/src/browser.c
@@ -94,6 +94,7 @@ browser_set_selected_row_iter (struct browser *browser, GtkTreeIter * iter)
 void
 browser_reset (gpointer data)
 {
+  printf("BROWSER_RESET\n");
   struct browser *browser = data;
   GtkListStore *list_store =
     GTK_LIST_STORE (gtk_tree_view_get_model (browser->view));
@@ -242,13 +243,17 @@ browser_file_match_extensions (struct browser *browser,
   const gchar *entry_ext;
   gchar **ext = browser->extensions;
 
+  printf("ELEKTROID_DIR: %c\n", (ELEKTROID_DIR+0));
+
   if (iter->item.type == ELEKTROID_DIR)
     {
+      printf("item equals ELEKTROID_DIR\n");
       return TRUE;
     }
 
   if (!ext)
     {
+      printf("ext does not exist\n");
       return TRUE;
     }
 
@@ -256,6 +261,7 @@ browser_file_match_extensions (struct browser *browser,
 
   if (!entry_ext)
     {
+      printf("entry_ext does not exist\n");
       return FALSE;
     }
```

I cannot make much sense of it yet, but I am trying...

**Comment by lentferj** [comment]
quite certain it does not enter this loop:
https://github.com/dagargo/elektroid/blob/master/src/browser.c#L286

But why - I don't know.

**Comment by lentferj** [comment]
Doesn't 
` while (!next_item_iterator (&iter))`
mean, that the while loop is not run, if "next item does not exist"? Wouldn't that mean, that processing stops at the forelast item?
Do we need a do {} while loop rather?

**Comment by dagargo** [comment]
At some point in the 2.0 development, I changed all the functions in the internal API's to return 0 when OK and something different when error. Therefore, the code is OK.

**Comment by lentferj** [comment]
I don't get why this line doesn't validate for the content of browser_local.dir

while (ret = !next_item_iterator (&iter))

**Comment by dagargo** [comment]
The code for reading a local directory is here.

https://github.com/dagargo/elektroid/blob/65a665df73cc6eb65305ea5276d94fdbb27b1f8c/src/local.c#L146-L159

Could you check what happens in line 159? What's the value of `data->dir`?

**Comment by lentferj** [comment]
data->dir is of type DIR (struct __dirstream ), I don't know how to print that

**Comment by dagargo** [comment]
Try with `data->path`, this contains the directory name (`char *`).

**Comment by lentferj** [comment]
ok, that worked and it gives back the same path that I pass via "-l".

**Comment by lentferj** [comment]
ok, so for the working case, this line matches

https://github.com/dagargo/elektroid/blob/master/src/local.c#L166

for the none working case it doesn't match .

**Comment by lentferj** [comment]
What is DT_DIR? I can't find where it is defined.....

**Comment by dagargo** [comment]
I've just pushed branch `sync_notifier_access`. It synchronizes access to the notifier struct and the file descriptor used for reading inotify events.

Now, it uses polling so the thread is not blocked. Perhaps this was the issue.

**Comment by dagargo** [comment]
`DT_DIR` is just part of `dirent.h`. Just type `man readdir`. But I acknowledge that the prefix `DT_` is completely misleading in this case.

**Comment by lentferj** [comment]
No, sync_notifier_access unfortunately does not solve this :/

**Comment by lentferj** [comment]
I am really at a loss here....  I added these print outs

```
diff --git a/src/local.c b/src/local.c
index 0c0e5c4..62a5204 100644
--- a/src/local.c
+++ b/src/local.c
@@ -156,8 +156,11 @@ local_next_dentry (struct item_iterator *iter)
       g_free (iter->item.name);
     }
 
+  printf("data->dir: %s\n", data->path);
   while ((dirent = readdir (data->dir)) != NULL)
     {
+      printf("data->dir: %s\n", data->path);
+      printf("dirent->d_name[012]: %c%c%c\n", dirent->d_name[0], dirent->d_name[1], dirent->d_name[2]);
       if (dirent->d_name[0] == '.')
        {
          continue;
@@ -165,6 +168,7 @@ local_next_dentry (struct item_iterator *iter)
 
       if (dirent->d_type == DT_DIR)
        {
+          printf("d_type == DT_DIR\n");
          iter->item.name = strdup (dirent->d_name);
          iter->item.type = ELEKTROID_DIR;
          iter->item.size = 0;
@@ -173,6 +177,7 @@ local_next_dentry (struct item_iterator *iter)
 
       if (dirent->d_type == DT_REG)
        {
+         printf("d_type == DT_REG\n");
          iter->item.name = strdup (dirent->d_name);
          iter->item.type = ELEKTROID_FILE;
          full_path = chain_path (data->path, dirent->d_name);
```

this is the directory structure

```
~/foobar$ ls -al
insgesamt 72
drwxrwxrwx   5 lentferj lentferj    69 Nov 30 12:12 .
drwxr-xr-x 209 lentferj lentferj 16384 Nov 30 12:13 ..
drwxr-xr-x   2 lentferj lentferj     6 Nov 30 12:12 1dir
-rw-r--r--   1 lentferj lentferj     0 Nov 30 12:12 1file
drwxr-xr-x   2 lentferj lentferj     6 Nov 30 12:12 2dir
drwxr-xr-x   2 lentferj lentferj     6 Nov 30 12:12 3dir
-rwxrwxrwx   1 lentferj lentferj 51438 Nov 29 15:17 FUN01.dnprj
```

and these are the print outs I get:
```
data->dir: /home/lentferj/foobar
data->dir: /home/lentferj/foobar
dirent->d_name[012]: .
data->dir: /home/lentferj/foobar
dirent->d_name[012]: ..
data->dir: /home/lentferj/foobar
dirent->d_name[012]: FUN
data->dir: /home/lentferj/foobar
dirent->d_name[012]: 1di
data->dir: /home/lentferj/foobar
dirent->d_name[012]: 2di
data->dir: /home/lentferj/foobar
dirent->d_name[012]: 3di
data->dir: /home/lentferj/foobar
dirent->d_name[012]: 1fi
ret: 0
entering end
```
So, the directories and files are "detected"... but they do not evaluate as DT_DIR or DT_REG which leaves me puzzled....

Adding 
`printf("dirent->d_type: %i\n", dirent->d_type);`

shows this

```
data->dir: /home/lentferj/foobar
data->dir: /home/lentferj/foobar
dirent->d_name[012]: .
dirent->d_type: 4
data->dir: /home/lentferj/foobar
dirent->d_name[012]: ..
dirent->d_type: 4
data->dir: /home/lentferj/foobar
dirent->d_name[012]: FUN
dirent->d_type: 0
data->dir: /home/lentferj/foobar
dirent->d_name[012]: 1di
dirent->d_type: 0
data->dir: /home/lentferj/foobar
dirent->d_name[012]: 2di
dirent->d_type: 0
data->dir: /home/lentferj/foobar
dirent->d_name[012]: 3di
dirent->d_type: 0
data->dir: /home/lentferj/foobar
dirent->d_name[012]: 1fi
dirent->d_type: 0
```
So, all directories and files return 0 for d_type... ???

**Comment by lentferj** [comment]
I thought that maybe the problem comes from the xfs file system, but actually both the working directory and the non-working one are on xfs filesystems (on different devices / mounts, though).

**Comment by dagargo** [comment]
This was another reason for this to fail but I was reluctant to accept this.

Be that as it may, there is a note in the man page of readdir about this and a quick search shows a [stackoverflow question](https://stackoverflow.com/questions/47078417/readdir-returning-dirent-with-d-type-dt-unknown-for-directories-and) discussing exactly this and blaming on XFS.

We'll need to call `stat`.

**Comment by dagargo** [comment]
I've read it's possible to format an XFS partition with an option to store this on the directory entries. Perhaps this is your case.

If the type is DT_UNKNOWN we'll need to call `stat`.

**Comment by dagargo** [comment]
c5056e267b126b4795c93099666abb4838fa54e5 should fix your issue.

Let me know if it does.

**Comment by lentferj** [comment]
yes, this fixes it. Thanks a ton!

**Comment by dagargo** [comment]
You're welcome.

Can we close this issue? Is the Digitone fully working with Elektroid now?

**Comment by lentferj** [comment]
Yes, from what I can see it fully works.

**Comment by dagargo** [comment]
Thanks, @lentferj.

Closed as solved.
